config/routes.rb
Chill::Application.routes.draw do
  get "file_uploads/files/:id/*file_path", to: 'original_files#show'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :notices do
    resources :search, only: [:index]
  end

  resources :notices, only: [:show, :new, :create] do
    collection do
      get :url_input
    end
    member do
      put :request_pdf
    end
  end

  resources :counter_notices, only: [:new, :create]

  namespace :entities do
    resources :search, only: [:index]
  end

  get '/n/:id', to: 'notices#show'
  get '/N/:id', to: 'notices#show'

  get '/submission_id/:id', to: 'submission_ids#show'
  get '/original_notice_id/:id', to: 'original_notice_ids#show'

  get '/original_news_id/:id', to: 'original_news_ids#show'

  resources :topics, only: [:show]

  scope format: true, constraints: { format: :json } do
    resources :topics, only: [:index]
  end

  resources :blog_entries, only: [:index, :show, :archive]
  get 'blog_feed', to: 'blog_entries#feed'
  get 'notices_feed', to: 'notices#feed'
  get 'blog_archive', to: 'blog_entries#archive'

  match :faceted_search, controller: 'notices/search', action: 'index'

  get "/twitter/international", to: "notices/search#index", defaults: {topics: "international, court orders, law enforcement requests, government requests", recipient_name: "twitter"}

  # N.B. no constraints on topics, that would require a db call
  match '/:recipient_name(/:topics)' => 'notices/search#index',
    constraints: { recipient_name: /Twitter|Google/i }

  root to: 'home#index'
end

app/models/blog_entry.rb
require 'recent_scope'
require 'validates_automatically'

class BlogEntry < ActiveRecord::Base
  extend RecentScope
  include ValidatesAutomatically

  # TODO: is the simple :author attribute enough? Does the Association
  # really give us anything?
  belongs_to :user

  has_many :blog_entry_topic_assignments, dependent: :destroy
  has_many :topics, through: :blog_entry_topic_assignments

  # must be defined before its use in validates_inclusion_of
  def self.valid_images
    imagery_directory = Rails.root.join('app/assets/images/blog/imagery')

    Dir["#{imagery_directory}/*.jpg"].map do |file|
      File.basename(file, '.jpg')
    end
  end

  validates_inclusion_of :image, in: valid_images, allow_nil: true

  def self.with_content
    where("url = '' or url IS NULL")
  end

  def self.we_are_reading
    where("url != '' and url IS NOT NULL")
  end

  def self.published
    where('published_at <= ?', Time.now).where(:archive => false).order('published_at DESC')
  end

  def self.archived
    where('published_at <= ?', Time.now).where(:archive => true).order('published_at DESC')
  end

  def self.recent_posts
    where('published_at <= ?', Time.now).where(:archive => false).where("url = '' or url IS NULL").order('published_at DESC').first(5)
  end

  def content_html
    Markdown.render(content.to_s)
  end

  def abstract_html
    Markdown.render(abstract.to_s)
  end

  # https://github.com/sferik/rails_admin/wiki/Enumeration
  def image_enum
    self.class.valid_images
  end

end

app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
  def index
    @blog_entries = BlogEntry.published.with_content.page(params[:page]).per(5)
    @we_are_reading = BlogEntry.published.we_are_reading.limit(5)
  end

  def archive
    @blog_entries = BlogEntry.archived.with_content.page(params[:page]).per(5)
    @we_are_reading = BlogEntry.published.we_are_reading.limit(5)
  end

  def show
    @blog_entry = BlogEntry.find(params[:id])
  end

  def feed
  	@blog_articles = BlogEntry.published.with_content.limit(5)
  	respond_to do |format|
  		format.rss { render :layout => false }
  	end
  end
end

app/helpers/blog_entry_helper.rb
module BlogEntryHelper
  def published_at(blog_entry)
    if published_at = blog_entry.published_at
      time_tag(published_at, published_at.to_s(:simple))
    end
  end

  def blog_search_engine_configured?
    Chill::Application.config.google_custom_blog_search_id
  end
end

app/views/blog_entries/_blog_entry.html.erb
<article class="post-item">
  <h3 class="title">
    <% if blog_entry.url.present? %>
      <%= link_to(blog_entry.title, blog_entry.url) %>
    <% else %>
      <%= link_to(blog_entry.title, blog_entry) %>
    <% end %>
  </h3>
  <%= render 'metadata', blog_entry: blog_entry %>
  <a class="snippet" href="<%= blog_entry_path(blog_entry) %>">
    <%= raw blog_entry.abstract_html %>
  </a>
</article>

app/views/blog_entries/_metadata.html.erb
<div class="metadata">
  <span class="author"><%= blog_entry.author %></span> on <%= published_at(blog_entry) %>
</div>

app/views/blog_entries/archive.html.erb
<% title 'Blog Archive' %>

<section class="posts">
  <%= render @blog_entries %>
</section>

<aside class="sidebar">
  <h4>What we're reading</h4>
  <ol>
    <% @we_are_reading.each do |blog_entry| %>
      <li><%= link_to(blog_entry.title, blog_entry.url) %></li>
    <% end %>
  </ol>
</aside>

<% if blog_search_engine_configured? %>
  <aside class="sidebar blog-search">
    <h4>Search the Blog</h4>
    <script>
      (function() {
        var cx = '<%= Chill::Application.config.google_custom_blog_search_id %>';
        var gcse = document.createElement('script');
        gcse.type = 'text/javascript';
        gcse.async = true;
        gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
            '//www.google.com/cse/cse.js?cx=' + cx;
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(gcse, s);
      })();
    </script>
    <gcse:search></gcse:search>
  </aside>
<% end %>

<section class="pagination-container">
  <%= paginate @blog_entries, outer_window: 0 %>
</section>

app/views/blog_entries/index.html.erb
<% title 'Blog' %>

<section class="posts">
  <%= render @blog_entries %>
</section>

<aside class="sidebar">
  <h4>What we're reading</h4>
  <ol>
    <% @we_are_reading.each do |blog_entry| %>
      <li><%= link_to(blog_entry.title, blog_entry.url) %></li>
    <% end %>
  </ol>
  <h4><%= link_to "Blog Archive", '/blog_archive' %></h4>
</aside>

<% if blog_search_engine_configured? %>
  <aside class="sidebar blog-search">
    <h4>Search the Blog</h4>
    <script>
      (function() {
        var cx = '<%= Chill::Application.config.google_custom_blog_search_id %>';
        var gcse = document.createElement('script');
        gcse.type = 'text/javascript';
        gcse.async = true;
        gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
            '//www.google.com/cse/cse.js?cx=' + cx;
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(gcse, s);
      })();
    </script>
    <gcse:search></gcse:search>
  </aside>
<% end %>

<section class="pagination-container">
  <%= paginate @blog_entries, outer_window: 0 %>
</section>

app/views/blog_entries/show.html.erb
<% title 'Blog', @blog_entry.title %>

<article class="post">
  <div class="imagery <%= @blog_entry.image %>"></div>
  <div class="content">
    <h3 class="title"><%= @blog_entry.title %></h1>
    <%= render 'metadata', blog_entry: @blog_entry %>
    <%= raw @blog_entry.content_html %>
  </div>
</article>