config/routes.rb
Chill::Application.routes.draw do
  get "file_uploads/files/:id/*file_path", to: 'original_files#show'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :notices do
    resources :search, only: [:index]
  end

  resources :notices, only: [:show, :new, :create] do
    collection do
      get :url_input
    end
    member do
      put :request_pdf
    end
  end

  resources :counter_notices, only: [:new, :create]

  namespace :entities do
    resources :search, only: [:index]
  end

  get '/n/:id', to: 'notices#show'
  get '/N/:id', to: 'notices#show'

  get '/submission_id/:id', to: 'submission_ids#show'
  get '/original_notice_id/:id', to: 'original_notice_ids#show'

  get '/original_news_id/:id', to: 'original_news_ids#show'

  resources :topics, only: [:show]

  scope format: true, constraints: { format: :json } do
    resources :topics, only: [:index]
  end

  resources :blog_entries, only: [:index, :show, :archive]
  get 'blog_feed', to: 'blog_entries#feed'
  get 'notices_feed', to: 'notices#feed'
  get 'blog_archive', to: 'blog_entries#archive'

  match :faceted_search, controller: 'notices/search', action: 'index'

  get "/twitter/international", to: "notices/search#index", defaults: {topics: "international, court orders, law enforcement requests, government requests", recipient_name: "twitter"}

  # N.B. no constraints on topics, that would require a db call
  match '/:recipient_name(/:topics)' => 'notices/search#index',
    constraints: { recipient_name: /Twitter|Google/i }

  root to: 'home#index'
end

app/models/entity.rb
require 'validates_automatically'
require 'hierarchical_relationships'
require 'entity_index_queuer'
require 'default_name_original'

class Entity < ActiveRecord::Base
  include Tire::Model::Search
  include ValidatesAutomatically
  include HierarchicalRelationships
  include DefaultNameOriginal

  PER_PAGE = 10
  HIGHLIGHTS = %i(name)

  belongs_to :user
  has_many :entity_notice_roles, dependent: :destroy
  has_many :notices, through: :entity_notice_roles

  delegate :publication_delay, to: :user, allow_nil: true

  mapping do
    columns.map(&:name).reject{|name| name == 'id'}.each do|column_name|
      indexes column_name
    end
    indexes :parent_id, as: 'parent_id'
  end

  KINDS = %w[organization individual]
  ADDITIONAL_DEDUPLICATION_FIELDS =
    %i(address_line_1 city state zip country_code phone email)

  validates_inclusion_of :kind, in: KINDS
  validates_uniqueness_of :name,
    scope: ADDITIONAL_DEDUPLICATION_FIELDS

  after_update { EntityIndexQueuer.for(self.id) }

  def attributes_for_deduplication
    all_deduplication_attributes = [
      :name, ADDITIONAL_DEDUPLICATION_FIELDS
    ].flatten

    attributes.select do |key, value|
      all_deduplication_attributes.include?(key.to_sym)
    end
  end

  def self.submitters
    submitter_ids = EntityNoticeRole.submitters.map(&:entity_id)

    where(id: submitter_ids)
  end
end

app/controllers/entities/search_controller.rb
class Entities::SearchController < ApplicationController

  def index
    search = entity_searcher.search
    @results = search.results

    respond_to do |format|
      format.json do
        render(
          json: @results,
          each_serializer: EntitySerializer,
          serializer: ActiveModel::ArraySerializer,
          root: 'entities',
          meta: meta_hash_for(@results)
        )
      end
    end
  end

  private

  def entity_searcher
    SearchesModels.new(params, Entity).tap do |searcher|
      if can?(:search, Entity)
        searcher.register TermSearch.new(:term, :_all)
      else
        searcher.register TermSearch.new(:term, [:name, :country_code, :url])
      end
    end
  end

end

app/views/entities/_address.html.erb
<span class="private">[Private]</span>
<span>
  <%= entity.city %>,
  <%= entity.state %>,
  <%= entity.zip %>,
  <%= entity.country_code.try(:upcase) %>
</span>

app/views/entities/_entity.html.erb
<% additional_css ||= '' %>
<% hide_identities = local_assigns.has_key?(:hide_identities) ? hide_identities : false %>
<section class="<%= role %> <%= additional_css %>">
  <h5><%= role %></h5>
  <h6>
    <% if hide_identities %>
      REDACTED
    <% else %>
      <%=
        link_to(
          entity.name,
          faceted_search_path("#{role}_name" => entity.name)
        )
      %>
    <% end %>
  </h6>

  <% if role == :sender && !hide_identities %>
    <% if notice.on_behalf_of_principal? %>
      <h6>
        <span class="on_behalf_of">on behalf of</span>
        <%=
          link_to(
            notice.principal_name,
            faceted_search_path('principal_name' => notice.principal_name)
          )
        %>
      </h6>
    <% end %>
    <%= render 'entities/address', entity: entity, role: role %>
    <span class="date sent">Sent on <%= date_sent(notice) %></span>
  <% elsif role == :recipient %>
    <%= render 'entities/address', entity: entity, role: role %>
    <span class="date received">Received on <%= date_received(notice) %></span>
  <% elsif role == :sender && entity.country_code.present? %>
    <span><%= t 'views.entities.entity.country' %>: <%= entity.country_code.upcase %></span>
  <% end %>
</section>