config/routes.rb
Chill::Application.routes.draw do
  get "file_uploads/files/:id/*file_path", to: 'original_files#show'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :notices do
    resources :search, only: [:index]
  end

  resources :notices, only: [:show, :new, :create] do
    collection do
      get :url_input
    end
    member do
      put :request_pdf
    end
  end

  resources :counter_notices, only: [:new, :create]

  namespace :entities do
    resources :search, only: [:index]
  end

  get '/n/:id', to: 'notices#show'
  get '/N/:id', to: 'notices#show'

  get '/submission_id/:id', to: 'submission_ids#show'
  get '/original_notice_id/:id', to: 'original_notice_ids#show'

  get '/original_news_id/:id', to: 'original_news_ids#show'

  resources :topics, only: [:show]

  scope format: true, constraints: { format: :json } do
    resources :topics, only: [:index]
  end

  resources :blog_entries, only: [:index, :show, :archive]
  get 'blog_feed', to: 'blog_entries#feed'
  get 'notices_feed', to: 'notices#feed'
  get 'blog_archive', to: 'blog_entries#archive'

  match :faceted_search, controller: 'notices/search', action: 'index'

  get "/twitter/international", to: "notices/search#index", defaults: {topics: "international, court orders, law enforcement requests, government requests", recipient_name: "twitter"}

  # N.B. no constraints on topics, that would require a db call
  match '/:recipient_name(/:topics)' => 'notices/search#index',
    constraints: { recipient_name: /Twitter|Google/i }

  root to: 'home#index'
end

app/views/shared/_footer.html.erb
<footer class="main">
  <div class="inner-wrapper">
    <span>&copy; 2015 Lumen</span>
    <nav>
	<%= link_to "License", page_path("license") %>	
    <%= link_to "Privacy", page_path("privacy") %>
    <%= link_to "Legal", page_path("legal") %>
    <%= link_to "Researchers", page_path("researchers") %>
    <% if user_signed_in? %>
      <%= link_to "Admin", rails_admin_path %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
    <% end %>
    </nav>
  </div>
</footer>

app/views/shared/_head.html.erb
<%= stylesheet_link_tag :application, :media => 'all' %>
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon" href="/favicon.ico">
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
<![endif]-->

app/views/shared/_header.html.erb
<header class="app">
  <div class="header-inner">
    <h1>
      <%= link_to root_path, :id => "root" do %>
        <%= image_tag("logo_2x.png", :size=> "265x64") %>
      <% end %>
    </h1>
    <%= render 'shared/navigation' -%>
    <div class="container header-bar">
      <h2><%= yield(:header) %></h2>
    </div>
  </div>
</header>

app/views/shared/_header_search.html.erb
<header class="app search-header">
  <div class="header-inner">
    <h1>
      <%= link_to root_path, :id => "root" do %>
        <%= image_tag("logo_2x.png", :size=> "265x64") %>
      <% end %>
    </h1>
    <%= render 'shared/navigation' -%>
    <div class="container search header-bar">
      <%= render 'shared/search' %>
    </div>
    <%= form_tag(notices_search_index_path, method: :get) do %>
      <div class="container advanced-search">
        <div class="width-wrapper">
          <h5>Advanced Search: <span>add additional search queries<span></h5>
          <% Notice::SEARCHABLE_FIELDS.each do |field| %>
            <%= render field %>
          <% end %>
          <a id="duplicate-field" href="javascript:void(0);" class="add-group">Add more</a>
          <div class="resubmit">
            <button class="button">Advanced Search</button>
          </div>
        </div>
      </div>
      <%= hidden_field_tag(:sort_by, params[:sort_by], class: 'sort_by_field') %>
    <% end %>
  </div>
</header>

<%= javascript_tag do -%>
  var active_advanced_search_parameters = <%= active_advanced_search_parameters? %>;
<% end %>

app/views/shared/_navigation.html.erb
<nav class="main-nav">
  <ol class="nav-list">
    <li class="nav-item search">
      <%= link_to("Search", root_path) %>
    </li>
    <li class="nav-item topics dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Topics</a>
      <div id="dropdown-topics" class="dropdown-menu" role="menu">
        <ol>
          <% topic_roots.each do |root| %>
            <%= render "shared/topic_dropdown", topic: root %>
          <% end %>
        </ol>
      </div>
    </li>
    <li class="nav-item new-notice">
      <%= link_to("Report a Demand", new_notice_path) %>
    </li>
    <li class="nav-item blog">
      <%= link_to("Blog", blog_entries_path) %>
    </li>
    <li class="nav-item about">
      <%= link_to "About", page_path("about") %>
    </li>
    <li class="nav-item research">
      <%= link_to "Research", page_path("research") %>
    </li>
  </ol>
</nav>

app/views/shared/_regulation_list.html.erb
<%- regulations.each do |regulation| %>
  <%= render regulation %><%- unless regulations.last == regulation %>, <% end %>
<% end %>

app/views/shared/_search.html.erb
<div class="search-wrapper">
  <%= form_tag(notices_search_index_path, method: :get) do %>
    <div class="input">
      <%= text_field_tag :term, params[:term], id: "search", type: 'search', placeholder: "Search all notices…" %>
    </div>
    <div class="submit">
      <button id="submit" class="" type="submit" title="search">Go</button>
      <div class="search-dropdown dropdown">
        <a id="toggle-advanced-search" href="" class="dropdown-toggle" data-toggle="dropdown">Open</a>
      </div>
    </div>
    <%= hidden_field_tag(:sort_by, params[:sort_by], class: 'sort_by_field') %>
  <% end %>
</div>

app/views/shared/_tag_list.html.erb
<%- tags.each do |tag| %>
  <%= render tag %><%- unless tags.last == tag %>, <% end %>
<% end %>

app/views/shared/_topic_dropdown.html.erb
<% has_children = topic.children.any? %>
<li class="<%= "dropdown-submenu" if has_children %>">
  <%= link_to(topic.name, topic_path(topic)) %>

  <% if has_children %>
    <ol class="dropdown-menu">
      <li class="title">Subtopics</li>
      <% topic.children.ordered.each do |child| %>
        <%= render "shared/topic_dropdown", topic: child %>
      <% end %>
    </ol>
  <% end %>
</li>

app/views/shared/_topic_list.html.erb
<% *init, last = topics %>
<% init.each do |topic| %>
  <%= link_to(topic.name, topic_path(topic)) %>, 
<% end %>
<%= link_to(last.name, topic_path(last)) if last %>