config/routes.rb
Chill::Application.routes.draw do
  get "file_uploads/files/:id/*file_path", to: 'original_files#show'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :notices do
    resources :search, only: [:index]
  end

  resources :notices, only: [:show, :new, :create] do
    collection do
      get :url_input
    end
    member do
      put :request_pdf
    end
  end

  resources :counter_notices, only: [:new, :create]

  namespace :entities do
    resources :search, only: [:index]
  end

  get '/n/:id', to: 'notices#show'
  get '/N/:id', to: 'notices#show'

  get '/submission_id/:id', to: 'submission_ids#show'
  get '/original_notice_id/:id', to: 'original_notice_ids#show'

  get '/original_news_id/:id', to: 'original_news_ids#show'

  resources :topics, only: [:show]

  scope format: true, constraints: { format: :json } do
    resources :topics, only: [:index]
  end

  resources :blog_entries, only: [:index, :show, :archive]
  get 'blog_feed', to: 'blog_entries#feed'
  get 'notices_feed', to: 'notices#feed'
  get 'blog_archive', to: 'blog_entries#archive'

  match :faceted_search, controller: 'notices/search', action: 'index'

  get "/twitter/international", to: "notices/search#index", defaults: {topics: "international, court orders, law enforcement requests, government requests", recipient_name: "twitter"}

  # N.B. no constraints on topics, that would require a db call
  match '/:recipient_name(/:topics)' => 'notices/search#index',
    constraints: { recipient_name: /Twitter|Google/i }

  root to: 'home#index'
end

app/controllers/entities/search_controller.rb
class Entities::SearchController < ApplicationController

  def index
    search = entity_searcher.search
    @results = search.results

    respond_to do |format|
      format.json do
        render(
          json: @results,
          each_serializer: EntitySerializer,
          serializer: ActiveModel::ArraySerializer,
          root: 'entities',
          meta: meta_hash_for(@results)
        )
      end
    end
  end

  private

  def entity_searcher
    SearchesModels.new(params, Entity).tap do |searcher|
      if can?(:search, Entity)
        searcher.register TermSearch.new(:term, :_all)
      else
        searcher.register TermSearch.new(:term, [:name, :country_code, :url])
      end
    end
  end

end

app/controllers/notices/search_controller.rb
class Notices::SearchController < ApplicationController
  layout 'search'

  def index

    respond_to do |format|
      format.html do
        @searcher = notice_searcher
      end
      format.json do
        results = notice_searcher.search.results
        render(
          json: results,
          each_serializer: NoticeSerializerProxy,
          serializer: ActiveModel::ArraySerializer,
          root: 'notices',
          meta: meta_hash_for(results)
        )
      end
    end
  end

  private

  def notice_searcher
    SearchesModels.new(params).tap do |searcher|
      Notice::SEARCHABLE_FIELDS.each do |searched_field|
        searcher.register searched_field
      end

      Notice::FILTERABLE_FIELDS.each do |filtered_field|
        searcher.register filtered_field
      end

      if params[:sort_by]
        searcher.sort_by = sort_by(params[:sort_by])
      end
    end
  end

  def sort_by(sort_by_param)
    sorting = Sortings.find(sort_by_param)
    sorting.sort_by
  end

end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  layout :resolve_layout

  before_filter :authenticate_via_token, only: :create

  def new
    if params[:type].blank?
      render :select_type and return
    end

    model_class = get_notice_type(params)

    @notice = model_class.new
    @notice.file_uploads.build(kind: 'original')
    model_class::DEFAULT_ENTITY_NOTICE_ROLES.each do |role|
      @notice.entity_notice_roles.build(name: role).build_entity(
        kind: default_kind_based_on_role(role)
      )
    end
    @notice.works.build do |notice|
      notice.copyrighted_urls.build
      notice.infringing_urls.build
    end
  end

  def create
    submission = SubmitNotice.new(
      get_notice_type(params[:notice]),
      notice_params
    )

    respond_to do |format|
      format.json do
        if cannot?(:submit, Notice)
          head :unauthorized and return
        end

        if submission.submit(current_user)
          head :created, location: submission.notice
        else
          render json: submission.errors, status: :unprocessable_entity
        end
      end

      format.html do
        if submission.submit(current_user)
          redirect_to :root, notice: "Notice created!"
        else
          @notice = submission.notice
          render :new
        end
      end
    end
  end

  def show
    if @notice = Notice.find(params[:id])
      respond_to do |format|
        format.html do
          if @notice.rescinded?
            render :rescinded
          elsif @notice.hidden || @notice.spam || !@notice.published
            render file: 'public/404_unavailable', formats: [:html], status: :not_found, layout: false
          else
            render :show
          end
        end

        format.json do
          serializer = researcher? ? NoticeSerializerProxy : LimitedNoticeSerializerProxy
          render json: @notice, serializer: serializer, root: json_root_for(@notice.class)  
        end
      end
    end
  end

  def url_input
    notice = get_notice_type(params).new
    @options = OpenStruct.new(
      notice: notice,
      url_type: params[:url_type].to_sym,
      main_index: params[:index].to_i,
      child_index: (Time.now.to_f * 10_000).to_i
    )
    notice.works.build do |w|
      w.copyrighted_urls.build
      w.infringing_urls.build
    end
  end

  def feed
    @recent_notices = Notice.visible.recent
    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

  def request_pdf
    @pdf = FileUpload.find(params[:id])
    @pdf.toggle!(:pdf_requested)
    render nothing: true
  end

  private

  def json_root_for(klass)
    klass.to_s.tableize.singularize
  end

  def notice_params
    params.require(:notice).permit(
      :title,
      :subject,
      :body,
      :date_sent,
      :date_received,
      :source,
      :tag_list,
      :jurisdiction_list,
      :regulation_list,
      :language,
      :action_taken,
      :request_type,
      :mark_registration_number,
      :url_count,
      :webform,
      topic_ids: [],
      file_uploads_attributes: [:kind, :file, :file_name],
      entity_notice_roles_attributes: [
        :entity_id,
        :name,
        entity_attributes: entity_params
      ],
      works_attributes: work_params
    )
  end

  def entity_params
    [:name, :kind, :address_line_1, :address_line_2, :city, :state,
     :zip, :country_code, :phone, :email, :url]
  end

  def work_params
    [
      :description, :kind, infringing_urls_attributes: [:url],
      copyrighted_urls_attributes: [:url],
    ]
  end

  def resolve_layout
    case action_name
    when "show"
      "search"
    when "url_input"
      false
    else
      "application"
    end
  end

  def get_notice_type(params)
    notice_type = params.fetch(:type, 'dmca').classify.constantize

    if notice_type < Notice
      notice_type
    else
      DMCA
    end

  rescue NameError
    DMCA
  ensure
    params.delete(:type)
  end

  def default_kind_based_on_role(role)
    if role == 'issuing_court'
      'organization'
    else
      'individual'
    end
  end

  def researcher?
    return false unless request.headers['HTTP_X_AUTHENTICATION_TOKEN']
    User.find_by_authentication_token(
      request.headers['HTTP_X_AUTHENTICATION_TOKEN']
    ).has_role?(Role.researcher)
  end
end

app/helpers/notices/search_helper.rb
module Notices::SearchHelper

  def on_behalf_of(sender_name, principal_name)
    raw %Q|#{ link_to(with_truncation(sender_name), faceted_search_path(sender_name: sender_name), class: 'sender') }
    <span class="on_behalf_of">on behalf of</span>
    #{ link_to(with_truncation(principal_name), faceted_search_path(principal_name: principal_name), class: 'principal') }|
  end

  def with_truncation(string)
    truncate(string, length: 20, omission: '…')
  end

  def formatted_facet_range_time(time)
    Time.at(time / 1000).to_datetime.to_s(:simple)
  end

  def range_facet_param(range)
    "#{range['from']}#{Notice::RANGE_SEPARATOR}#{range['to']}"
  end

  def facet_dropdown_active_indicator(type)
    if params[type].present? || params[unspecified_identifiers(type)].present?
      'active'
    end
  end

  def facet_active_indicator(type, facet_value)
    if param_matches?(type, facet_value) || param_unspecified?(type, facet_value)
      'active'
    end
  end

  def param_matches?(type, facet_value)
    params[type].present? && params[type] == facet_value
  end

  def param_unspecified?(type, facet_value)
    facet_value.blank? && params[unspecified_identifiers(type)]
  end

  def unspecified_identifiers(parameter)
    @unspecified_identifiers ||= HashWithIndifferentAccess.new do |hash, key|
      hash[key] = UnspecifiedTermFilter.unspecified_identifier(key)
    end
    @unspecified_identifiers[parameter]
  end

  def sort_order_label(sort_by_param)
    sorting = Sortings.find(sort_by_param)
    sorting.label
  end
end

app/helpers/notices_helper.rb
module NoticesHelper

  def form_partial_for(instance)
    "#{instance.type.tableize.singularize}_form"
  end

  def show_partial_for(instance)
    "#{instance.type.tableize.singularize}_show"
  end

  def works_partial_for(instance)
    "#{instance.type.tableize.singularize}_works"
  end

  def display_date_field(record, field)
    if date = record.send(field)
      time_tag date, date.to_s(:simple)
    end
  end

  def date_sent(notice)
    display_date_field(notice, :date_sent)
  end

  def date_received(notice)
    display_date_field(notice, :date_received)
  end

  def subject(notice)
    if notice.subject.present?
      notice.subject
    else
      'Unknown'
    end
  end

  def sent_via(notice)
    if notice.source.present?
      notice.source
    else
      'Unknown'
    end
  end

  def iso_countries
    CountrySelect::ISO_COUNTRIES_FOR_SELECT
  end

  def first_time_visitor_content
    Markdown.render( t('first_time_visitor') )
  end

  def label_for_url_input(url_type, notice)
    case url_type
    when :infringing_urls
      case notice
      when ::DMCA, ::Trademark
        "Allegedly Infringing URL"
      when ::PrivateInformation
        "URL with private information"
      when ::CourtOrder
        "Targeted URL"
      when ::DataProtection, ::LawEnforcementRequest
        "URL mentioned in request"
      when ::Defamation
        "Allegedly Defamatory URL"
      when ::Other
        "Problematic URL"
      end
    when :copyrighted_urls
      case notice
      when ::DMCA, ::Other
        "Original Work URL"
      when ::LawEnforcementRequest
        "URL of original work"
      end
    else
      fail "Unknown url_type: #{url_type}"
    end
  end
end

app/views/notices/search/_date_range_filter.html.erb
<li class="dropdown <%= date_range_filter.parameter %> <%= facet_dropdown_active_indicator(date_range_filter.parameter) %>">
  <a class="dropdown-toggle title <%= date_range_filter.parameter %>" data-toggle="dropdown" href="javascript:void(0);">
    <%= date_range_filter.title %>
  </a>
  <ol class="dropdown-menu <%= date_range_filter.parameter %>" role="menu">
    <li class="facet"><a href="javascript:void(0);" data-facet-name="<%= date_range_filter.parameter %>" data-value="">All</a></li>
    <% results.facets[date_range_filter.parameter.to_s]['ranges'].each do |range| %>
      <li class="facet <%= facet_active_indicator(date_range_filter.parameter, range_facet_param(range)) %>" name="<%= date_range_filter.parameter %>" >
      <a href="javascript:void(0);" data-facet-name="<%= date_range_filter.parameter %>" data-value="<%= range_facet_param(range) %>">Since <%= formatted_facet_range_time(range['from']) %><span class="total-count"><%= range['count'] %> Results</span></a>
      </li>
    <% end %>
  </ol>
  <%= hidden_field_tag(date_range_filter.parameter, params[date_range_filter.parameter]) %>
</li>

app/views/notices/search/_result.html.erb
<%= content_tag_for(:li, result, class: "result") do %>
  <h3 class="title"><%= link_to result.title, notice_path(result.id) %></h3>
  <div class="metadata">
    <div class="date-received"><%= date_received(result) %></div>
    <div class="sender-receiver">
      <% if result.on_behalf_of_principal? %>
        <%= on_behalf_of(result.sender_name, result.principal_name) %>
      <% else %>
        <% if result.sender_name.present? %>
          <%= link_to(result.sender_name, faceted_search_path(sender_name: result.sender_name), class: 'sender' )%>
        <% elsif result.principal_name.present? %>
          <%= link_to(result.principal_name, faceted_search_path(principal_name: result.principal_name), class: 'principal' )%>
        <% end %>
      <% end %>
      <span class="arrow"><%= image_tag 'arrow-small.svg' %></span>
      <% if result.recipient_name.present? %>
        <%= link_to(result.recipient_name, faceted_search_path(recipient_name: result.recipient_name), class: 'receiver' )%>
      <% end %>
    </div>
    <ol class="excerpt">
      <% result.with_excerpts do |excerpt| %>
        <li class="excerpt">
          <%= sanitize(excerpt, tags: 'em') %>
        </li>
      <% end %>
    </ol>
    <div class="topic">
      <%= render 'shared/topic_list', topics: result.topics %>
    </div>
  </div>
<% end %>

app/views/notices/search/_term_filter.html.erb
<li class="dropdown <%= term_filter.parameter %> <%= facet_dropdown_active_indicator(term_filter.parameter) %>">
<a class="dropdown-toggle title <%= term_filter.parameter %>" data-toggle="dropdown" href="javascript:void(0);">
  <%= term_filter.title %>
</a>
  <ol class="dropdown-menu <%= term_filter.parameter %>" role="menu">
    <li class="facet"><a href="javascript:void(0);" data-facet-name="<%= term_filter.parameter %>" data-value="">All</a></li>
    <% unspecified_identifier = unspecified_identifiers(term_filter.parameter) %>
    <% results.facets[term_filter.parameter.to_s]['terms'].each do |term| %>
      <% name = term['term'] %>
      <% unspecified = name.blank? %>
      <% active_indicator = facet_active_indicator(term_filter.parameter, name) %>
      <li class="facet <%= active_indicator %>" name="<%= term_filter.parameter %>">
      <% data_hash = {
        facet_name: term_filter.parameter,
        unspecified_name: unspecified_identifier
      } %>
      <% data_hash[:value] = name unless unspecified %>
      <%= link_to "javascript:void(0);", data: data_hash do %>
        <%= unspecified ? 'Unspecified' : name %><span class="total-count"><%= term['count'] %> Results</span>
      <% end %>
      </li>
    <% end %>
  </ol>
  <%= hidden_field_tag(term_filter.parameter, params[term_filter.parameter]) %>
  <%= hidden_field_tag(unspecified_identifier, params[unspecified_identifier], class: 'unspecified') %>
</li>

app/views/notices/search/_term_search.html.erb
<%=
  content_tag(
    :div, '',
    class: 'search-field-data',
    style: 'display:none;',
    data: {
      title: term_search.title,
      parameter: term_search.parameter,
      value: params[term_search.parameter],
      all_words: params["#{term_search.parameter}-require-all"]
    }
  )
%>

app/views/notices/search/index.html.erb
<%= title 'Search' %>
<%= cache(@searcher.cache_key) do %>
<% results = @searcher.search.results -%>

<section class="search-results">
  <header>
    <%= form_tag(notices_search_index_path, method: :get, id: 'facets-form') do %>
      <% if results.facets %>
        <ol class="results-facets">
          <li class="title"><span>Facets<span></li>
            <% Notice::FILTERABLE_FIELDS.each do |filterable_field| %>
              <%= render filterable_field, results: results %>
            <% end %>
            <li class="title results-context-toggle">About Facets</li>
        </ol>
      <% end %>
      <%= hidden_field_tag(:sort_by, params[:sort_by], class: 'sort_by_field') %>
    <% end %>
    <div class="results-context" style="display:none;">
      Choosing to view a particular facet of the results does not filter the results. While the immediate view of the results will change to reflect the choice of facet(s), all of the original search’s totals will remain in the dropdowns.
    </div>
    <div class="result-stats">
      <span class="total-entries">Found <%= results.total_entries %> results</span>
      <div class="dropdown sort-order">
        Sort by: <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)"><%= sort_order_label(params[:sort_by]) %></a>
        <ol class="dropdown-menu" role="menu">
          <% Notice::SORTINGS.each do |sorting| %>
            <li class="facet">
            <%=
              link_to(
                sorting.label, '#', 'data-value' => sorting.key,
                'data-label' => sorting.label
              ) %>
            </li>
          <% end %>
        </ol>
      </div>
    </div>
  </header>
  <ol class="results-list">
    <%= render partial: 'result', collection: results %>
  </ol>
  <%= paginate results, left: 9, right: 2 %>
</section>
<% end %>